### ISSUE TITLE
Fix with directions check box

### ISSUE THREAD

**Issue by LeeJMorel** [randofan/MyCalendar#11]
**Describe the bug**
There are issues when downloading files with and without directions. The directions seem to have no effect.

**To Reproduce**
1. Launch the MyCalendar extension.
2. Click on the "with directions" checkbox.
3. Click download the file
4. Run it on your calendar

**Expected behavior**
I expected the downloaded files to include the directions and for them to have an effect.

**Desktop**
- OS: Windows 11
- Browser: Chrome

**Comment by randofan** [comment]
A UW maps link should be included in the description of the calendar event. Could you provide a screenshot of the incorrect behavior?

**Comment by uwthcho** [comment]
This bug was reported before the directions functionality was implemented. It now works.
