### ISSUE TITLE
Save checkbox has no function

### ISSUE THREAD

**Issue by LeeJMorel** [randofan/MyCalendar#12]
**Describe the bug**
The "save" functionality within the extension needs clarification as it currently appears to have no functionality, and it is unclear what its intended functionality is supposed to be. It is also unclear if multiple plans can be saved and how to load and manage those files.

**To Reproduce**
1. Launch the MyCalendar extension.
2. Click on the "save" checkbox.
3. Click download the file
4. Run it on your calendar

**Expected behavior**
I expected the "save" functionality to have a clear purpose and perform the intended action of saving and managing plans. It should provide clarity on how to save multiple plans and how to load and manage those files.

**Desktop**
- OS: Windows 11
- Browser: Chrome

**Comment by randofan** [comment]
The save checkbox is only for the preferences. At the moment, preferences only include the building location. Additional preferences are opportunities for future work.

**Comment by randofan** [comment]
See https://github.com/randofan/MyCalendar/pull/26
