### ISSUE TITLE
Classes do not save to the correct quarter

### ISSUE THREAD

**Issue by LeeJMorel** [randofan/MyCalendar#13]
**Describe the bug**
Changing quarters results in the overwrite of current quarter classes, and it does not load the classes to their correct quarter, leading to a critical bug.

**To Reproduce**
1. Launch the MyCalendar extension.
2. Click on the "save" checkbox.
3. Click download the file
4. Run it on your calendar

**Expected behavior**
I expected that changing quarters would correctly load the classes to their respective quarters without overwriting the existing quarter's classes.

**Desktop**
- OS: Windows 11
- Browser: Chrome

**Comment by randofan** [comment]
Yup! This was a feature we weren't able to implement yet during Beta release. We've since finished it.
