### ISSUE TITLE
Error when trying to download .ics if a class has to be arranged.

### ISSUE THREAD

**Issue by Zanderthegreat12** [randofan/MyCalendar#20]
If there is a class that has "to be arranged" in the table then .ics wouldn't download my schedule.

**Comment by randofan** [comment]
@uwthcho working on this problem right now. We're deciding to just gray out the checkbox if there isn't a time the lecture meets at

**Comment by uwthcho** [comment]
PR: https://github.com/randofan/MyCalendar/pull/25
